repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T01--Betty-Snyder
repo_name: 2025-1-T01--Betty-Snyder
site_name: Grupo Betty Snyder - Turma 1 (2025.1)
site_description: Documentação do projeto do grupo Betty Snyder de Qualidade de Software (2025.1), Turma 1
nav:
  - Home: index.md
  - Fase 1 - Propósito de avaliação: processo-avaliacao/processo_de_avaliacao.md
  - Fase 2 - Especificação:
    - Abordagem GQM: gqm/gqm.md
    - Abstraction Sheets: gqm/abstract.md
  - Fase 3 - Projetar avaliação:
    - Plano de Avaliação: plano-avaliacao/plano_avaliacao.md
  - Fase 4 - Executar avaliação:
    - Medidas Obtidas - Usabilidade:
      - M1: medidas-obtidas/usabilidade/usabilidade-m1.md
      - M2: medidas-obtidas/usabilidade/usabilidade-m2.md
      - M3: medidas-obtidas/usabilidade/usabilidade-m3.md
      - M4: medidas-obtidas/usabilidade/usabilidade-m4.md
      - M5: medidas-obtidas/usabilidade/usabilidade-m5.md
      - M6: medidas-obtidas/usabilidade/usabilidade-m6.md
      - M7: medidas-obtidas/usabilidade/usabilidade-m7.md
      - M8: medidas-obtidas/usabilidade/usabilidade-m8.md
    - Medidas Obtidas - Confiabilidade:
      - M1: medidas-obtidas/confiabilidade/confiabilidade-m1.md
      - M2: medidas-obtidas/confiabilidade/confiabilidade-m2.md
      - M3: medidas-obtidas/confiabilidade/confiabilidade-m3.md
    - Comparação com os Critérios e Julgamentos: 
      - Usabilidade: medidas-obtidas/comparacao/usabilidade.md
      - Confiabilidade: medidas-obtidas/comparacao/confiabilidade.md
  - Entrega Final:
    - Métricas de Avaliação do Processo: trabalho-final/metricas_de_avaliacao_do_projeto_agromart.md
    - Relatório Final: trabalho-final/relatorio.md 
    - Ações de Melhoria Sugeridas:
      - Usabilidade: trabalho-final/melhorias/usabilidade.md
      - Confiabilidade: trabalho-final/melhorias/confiabilidade.md 
    - Slides de apresentação: trabalho-final/slides.md
    - Protótipo de Alta Fidelidade: trabalho-final/prototipo.md

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: teal

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
    - scheme: high-contrast
      primary: black
      accent: yellow
      toggle:
        icon: material/weather-cloudy-alert
        name: Switch to high contrast
  logo: assets/img/logo1.png
  extra_css: [stylesheets/extra.css]
markdown_extensions:
  - attr_list
